// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJyxf5k8tGYdOVAkReGyQNc79YPUW5DDA',
    appId: '1:177728232626:android:9969473fd6da185c62fdab',
    messagingSenderId: '177728232626',
    projectId: 'connect-200a',
    storageBucket: 'connect-200a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEP4kbrghd32lUPjG-G2unzdXXi4TAMIE',
    appId: '1:177728232626:ios:c52936438b2c1b9062fdab',
    messagingSenderId: '177728232626',
    projectId: 'connect-200a',
    storageBucket: 'connect-200a.firebasestorage.app',
    androidClientId: '177728232626-tvnofqp7gksaeb602dtlm99rn6m618ig.apps.googleusercontent.com',
    iosClientId: '177728232626-kb6nvvvpf0dlsp8sn5s34nl6i7ire08o.apps.googleusercontent.com',
    iosBundleId: 'com.example.connect',
  );

}